version: '3'
networks:
    udp_networks:
      ipam: #ip address management
        config:
          - subnet: 172.30.0.0/24
            gateway: 172.30.0.1

services:
  iot_gateway:
    build: ./IOT_gateway
    container_name: "iot_gateway"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.2
    depends_on:
      - cloud_server

  sensor_devices:
    container_name: "sensor_devices"
    build: ./UDP_client
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.3
    depends_on:
      - iot_gateway

  cloud_server:
    build: ./Cloud_server
    container_name: "cloud_server"
    tty: true
    ports:
      - 127.0.0.1:8085:50000
    networks:
      udp_networks:
        ipv4_address: 172.30.0.4
    depends_on:
      - my_database
    
  my_database:
    build: ./Cloud_server/Database
    container_name: "my_database"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.5

  mqtt_adapter:
    container_name: "mqtt_adapter"
    build: ./MQTT_client/MQTT_subs
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.6

  mqtt_sensor_devices:
    container_name: "mqtt_sensor_devices"
    build: ./MQTT_client/MQTT_pub
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.7
    depends_on:
      - mqtt_adapter