version: '3'
networks:
    udp_networks:
      ipam: #ip address management
        config:
          - subnet: 172.30.0.0/24
            gateway: 172.30.0.1

services:
  iot_gateway:
    build: ./IOT_gateway
    container_name: "iot_gateway"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.2
    depends_on:
      - cloud_server

  sensor_devices:
    container_name: "sensor_devices"
    build: ./UDP_client
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.3
    depends_on:
      - iot_gateway

  cloud_server:
    build: ./Cloud_server
    container_name: "cloud_server"
    tty: true
    ports:
      - 127.0.0.1:8085:50000
    networks:
      udp_networks:
        ipv4_address: 172.30.0.4
    depends_on:
      - db_coordinator
    
  db_coordinator:
    build:
      context: ./Cloud_server/Database
      target: db_coordinator
    container_name: "db_coordinator"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.5
    depends_on:
      - database1
      - database2

  database1:
    build:
      context: ./Cloud_server/Database
      target: database1
    container_name: "database1"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.8

  database2:
    build:
      context: ./Cloud_server/Database
      target: database2
    container_name: "database2"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.9

  mqtt_adapter:
    container_name: "mqtt_adapter"
    build: ./MQTT_client/MQTT_subs
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.6
    depends_on:
      - iot_gateway

  mqtt_sensor_devices:
    container_name: "mqtt_sensor_devices"
    build: ./MQTT_client/MQTT_pub
    networks:
      udp_networks:
        ipv4_address: 172.30.0.7
    depends_on:
      - mqtt_adapter