version: '3'
networks:
    udp_networks:
      ipam: #ip address management
        config:
          - subnet: 172.30.0.0/24
            gateway: 172.30.0.1

services:
  iot_gateway:
    build: ./IOT_gateway
    container_name: "iot_gateway"
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.2

  sensor_devices:
    build: ./UDP_client
    tty: true
    networks:
      udp_networks:
        ipv4_address: 172.30.0.3